name: Build and Release Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o build/vttParser-${{ matrix.goos }}-${{ matrix.goarch }}
      
      - name: Compress binaries
        run: |
          cd build
          tar -czf vttParser-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz vttParser-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vttParser-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          path: build/vttParser-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
      
      - name: Display structure
        run: ls -R
      
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/**
          tag_name: ${{ steps.bump.outputs.new_tag }}
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}